CREATE TABLE HSE_DATA_AUDITD
(
  FACT_NO     VARCHAR2(4 BYTE)                  NOT NULL,
  SUBMIT_ID   VARCHAR2(50 BYTE)                 NOT NULL,
  SUBMIT_SEQ  VARCHAR2(3 BYTE)                  NOT NULL,
  SASPECT_NO  VARCHAR2(4 BYTE)                  NOT NULL,
  SCORE       NUMBER                            NOT NULL,
  TOTAL       NUMBER                            NOT NULL,
  DESC_ISSUE  VARCHAR2(50 BYTE),
  REMARK      VARCHAR2(30 BYTE)
)
TABLESPACE SIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE HSE_DATA_AUDITD ADD (
  CONSTRAINT PK_HSE_DATA_AUDITD
 PRIMARY KEY
 (FACT_NO, SUBMIT_ID, SUBMIT_SEQ) DISABLE);


