CREATE TABLE HSE_DATA_SUB_ASPECT
(
  FACT_NO     VARCHAR2(4 BYTE)                  NOT NULL,
  SASPECT_NO  VARCHAR2(4 BYTE)                  NOT NULL,
  SASPECT_NM  VARCHAR2(200 BYTE),
  VAL_WEIGHT  FLOAT(126),
  SORT_SEQ    VARCHAR2(3 BYTE),
  STOP_MK     VARCHAR2(1 BYTE),
  ASPECT_NO   VARCHAR2(2 BYTE),
  DIM_SEQ     VARCHAR2(3 BYTE)
)
TABLESPACE SIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE HSE_DATA_SUB_ASPECT ADD (
  CONSTRAINT PK_HSE_DATA_SUB_ASPECT
 PRIMARY KEY
 (FACT_NO, SASPECT_NO) DISABLE);


