CREATE TABLE HSE_DATA_AUDITM
(
  FACT_NO      VARCHAR2(4 BYTE)                 NOT NULL,
  SUBMIT_ID    VARCHAR2(50 BYTE)                NOT NULL,
  SUBMIT_DATE  VARCHAR2(14 BYTE)                NOT NULL,
  SUBMIT_USER  VARCHAR2(50 BYTE)                NOT NULL,
  AREA_NO      VARCHAR2(2 BYTE)                 NOT NULL,
  BUILD_NO     VARCHAR2(2 BYTE)                 NOT NULL,
  AUDITEE      VARCHAR2(50 BYTE),
  AUDITOR      VARCHAR2(50 BYTE),
  CHECK_DATE   VARCHAR2(14 BYTE)                NOT NULL,
  MODIFY_DATE  VARCHAR2(14 BYTE),
  MODIFY_USER  VARCHAR2(50 BYTE),
  LTI          NUMBER,
  NLTI         NUMBER,
  LOST_DAY     NUMBER
)
TABLESPACE SIS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE HSE_DATA_AUDITM ADD (
  CONSTRAINT PK_HSE_DATA_AUDITM
 PRIMARY KEY
 (FACT_NO, SUBMIT_ID) DISABLE);


